const recentsDummyData = [
  {
    dateAdded: 1534659705706,
    id: '160',
    index: 5,
    parentId: '1',
    title: 'Extensions',
    url: 'chrome://extensions/',
  },
  {
    dateAdded: 1534647840480,
    id: '159',
    index: 2,
    parentId: '21',
    title: 'Awesome websites about Creative Front End Development',
    url: 'http://www.creativelang.com/list/#/',
  },
  {
    dateAdded: 1534578339758,
    id: '157',
    index: 1,
    parentId: '21',
    title: 'YouTube to MP3 Converter - The Best Online - YTBmp3',
    url: 'https://www.ytbmp3.com/',
  },
  {
    dateAdded: 1532856789883,
    id: '155',
    index: 27,
    parentId: '1',
    title: 'CSS Selectors Reference',
    url: 'https://www.w3schools.com/cssref/css_selectors.asp',
  },
  {
    dateAdded: 1532842355613,
    id: '154',
    index: 26,
    parentId: '1',
    title: 'Setting up ESLint on VS Code with Airbnb JavaScript Style Guide',
    url: 'https://travishorn.com/setting-up-eslint-on-vs-code-with-airbnb-javascript-style-guide-6eb78a535ba6',
  },
  {
    dateAdded: 1530972675818,
    id: '19',
    index: 6,
    parentId: '1',
    title: 'Postman - Chrome Web Store',
    url: 'https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop/related?hl=en',
  },
  {
    dateAdded: 1524319882148,
    id: '13',
    index: 4,
    parentId: '1',
    title: 'Add Existing Project To Git Repo',
    url: 'https://gist.github.com/alexpchin/102854243cd066f8b88e',
  },
  {
    dateAdded: 1524242365836,
    id: '11',
    index: 3,
    parentId: '1',
    title: '10 new open-source Bootstrap themes',
    url: 'https://hackerthemes.com/new-bootstrap-themes/',
  },
  {
    dateAdded: 1523801426858,
    id: '9',
    index: 2,
    parentId: '1',
    title: 'Edit fiddle - JSFiddle',
    url: 'https://jsfiddle.net/jnjxboeo/2/',
  },
];

const folderDummyData = [
  {
    children: [
      {
        dateAdded: 1532501462554,
        id: '147',
        index: 1,
        parentId: '144',
        title: 'DEV Community 👩‍💻👨‍💻 - Where software engineers connect, build their resumes, and grow.',
        url: 'https://dev.to/',
      },
      {
        dateAdded: 1532501475605,
        id: '148',
        index: 2,
        parentId: '144',
        title: 'Philippines - all about the Philippines',
        url: 'https://old.reddit.com/r/Philippines/#res:ner-page=2',
      },
      {
        dateAdded: 1522298550525,
        id: 5,
        index: 0,
        parentId: '144',
        title: 'Piracy Megathread v2.0 : Piracy',
        url: 'https://www.reddit.com/r/Piracy/comments/6583hl/piracy_megathread_v20/',
      },
      {
        dateAdded: 1533002645254,
        id: '156',
        index: 4,
        parentId: '144',
        title: 'Overview — Bitbucket',
        url: 'https://bitbucket.org/dashboard/overview',
      },
      {
        dateAdded: 1530972675818,
        id: '19',
        index: 5,
        parentId: '144',
        title: 'Postman - Chrome Web Store',
        url: 'https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop/related?hl=en',
      },
    ],
    dateAdded: 1532501359870,
    dateGroupModified: 1533004793110,
    id: '144',
    index: 0,
    parentId: '1',
    title: 'Pins',
  },
];

const wholeBookmarksDummyData = [
  {
    children: [
      {
        children: [
          {
            dateAdded: 1523801426858,
            id: '9',
            index: 2,
            parentId: '1',
            title: 'Edit fiddle - JSFiddle',
            url: 'https://jsfiddle.net/',
          },
          {
            dateAdded: 1524242365836,
            id: '11',
            index: 3,
            parentId: '1',
            title: '10 new open-source Bootstrap themes',
            url: 'https://hackerthemes.com/new-bootstrap-themes/',
          },
          {
            dateAdded: 1524319882148,
            id: '13',
            index: 4,
            parentId: '1',
            title: 'Add Existing Project To Git Repo',
            url: 'https://gist.github.com/alexpchin/102854243cd066f8b88e',
          },
          {
            dateAdded: 1534659705706,
            id: '160',
            index: 5,
            parentId: '1',
            title: 'Extensions',
            url: 'chrome://extensions/',
          },
          {
            dateAdded: 1530972675818,
            id: '19',
            index: 6,
            parentId: '1',
            title: 'Postman - Chrome Web Store',
            url: 'https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop/related?hl=en',
          },
          {
            children: [
              {
                dateAdded: 1534578339758,
                id: '157',
                index: 1,
                parentId: '21',
                title: 'YouTube to MP3 Converter - The Best Online - YTBmp3',
                url: 'https://www.ytbmp3.com/',
              },
              {
                dateAdded: 1534647840480,
                id: '159',
                index: 2,
                parentId: '21',
                title: 'Awesome websites about Creative Front End Development',
                url: 'http://www.creativelang.com/list/#/',
              },
            ],
            dateAdded: 1532778337889,
            dateGroupModified: 1534659705706,
            id: '21',
            index: 7,
            parentId: '1',
            title: 'aaaa',
          },
          {
            children: [
              {
                dateAdded: 1462721952000,
                id: '52',
                index: 1,
                parentId: '50',
                title: 'Seamless Patterns',
                url: 'http://subtlepatterns.com/page/4/',
              },
              {
                dateAdded: 1463815589000,
                id: '55',
                index: 4,
                parentId: '50',
                title: 'Color Pallete',
                url: 'http://www.colorion.co/',
              },
              {
                dateAdded: 1484146898000,
                id: '58',
                index: 7,
                parentId: '50',
                title: 'Piskel - Free online sprite editor',
                url: 'http://www.piskelapp.com/',
              },
            ],
            dateAdded: 1532841215445,
            id: '50',
            index: 10,
            parentId: '1',
            title: 'Aesthetics',
          },
          {
            dateAdded: 1485430523000,
            id: '150',
            index: 22,
            parentId: '1',
            title: 'Markdown Cheatsheet · adam-p/markdown-here Wiki',
            url: 'https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet',
          },
          {
            dateAdded: 1532856789883,
            id: '155',
            index: 27,
            parentId: '1',
            title: 'CSS Selectors Reference',
            url: 'https://www.w3schools.com/cssref/css_selectors.asp',
          },
        ],
        dateAdded: 1522296844518,
        dateGroupModified: 1534760603068,
        id: '1',
        index: 0,
        parentId: '0',
        title: 'Bookmarks bar',
      },
      {
        children: [
          {
            dateAdded: 1493377594000,
            id: '147',
            index: 0,
            parentId: '2',
            title: 'p5.js | reference',
            url: 'https://p5js.org/reference/',
          },
        ],
        dateAdded: 1522296844518,
        dateGroupModified: 1534760608419,
        id: '2',
        index: 1,
        parentId: '0',
        title: 'Other bookmarks',
      },
    ],
    dateAdded: 1534741829513,
    id: '0',
    title: '',
  },
];

export { folderDummyData, recentsDummyData, wholeBookmarksDummyData };
