const recentsDummyData = [
  {
    dateAdded: 1534659705706,
    id: '160',
    index: 5,
    parentId: '1',
    title: 'Extensions',
    url: 'chrome://extensions/',
  },
  {
    dateAdded: 1534647840480,
    id: '159',
    index: 2,
    parentId: '21',
    title: 'Awesome websites about Creative Front End Development',
    url: 'http://www.creativelang.com/list/#/',
  },
  {
    dateAdded: 1534578339758,
    id: '157',
    index: 1,
    parentId: '21',
    title: 'YouTube to MP3 Converter - The Best Online - YTBmp3',
    url: 'https://www.ytbmp3.com/',
  },
  {
    dateAdded: 1532856789883,
    id: '155',
    index: 27,
    parentId: '1',
    title: 'CSS Selectors Reference',
    url: 'https://www.w3schools.com/cssref/css_selectors.asp',
  },
  {
    dateAdded: 1532842355613,
    id: '154',
    index: 26,
    parentId: '1',
    title: 'Setting up ESLint on VS Code with Airbnb JavaScript Style Guide',
    url: 'https://travishorn.com/setting-up-eslint-on-vs-code-with-airbnb-javascript-style-guide-6eb78a535ba6',
  },
  {
    dateAdded: 1530972675818,
    id: '19',
    index: 6,
    parentId: '1',
    title: 'Postman - Chrome Web Store',
    url: 'https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop/related?hl=en',
  },
  {
    dateAdded: 1524319882148,
    id: '13',
    index: 4,
    parentId: '1',
    title: 'Add Existing Project To Git Repo',
    url: 'https://gist.github.com/alexpchin/102854243cd066f8b88e',
  },
  {
    dateAdded: 1524242365836,
    id: '11',
    index: 3,
    parentId: '1',
    title: '10 new open-source Bootstrap themes',
    url: 'https://hackerthemes.com/new-bootstrap-themes/',
  },
  {
    dateAdded: 1523801426858,
    id: '9',
    index: 2,
    parentId: '1',
    title: 'Edit fiddle - JSFiddle',
    url: 'https://jsfiddle.net/jnjxboeo/2/',
  },
];

const folderDummyData = [
  {
    children: [
      {
        dateAdded: 1532501462554,
        id: '147',
        index: 1,
        parentId: '144',
        title: 'DEV Community 👩‍💻👨‍💻 - Where software engineers connect, build their resumes, and grow.',
        url: 'https://dev.to/',
      },
      {
        dateAdded: 1532501475605,
        id: '148',
        index: 2,
        parentId: '144',
        title: 'Philippines - all about the Philippines',
        url: 'https://old.reddit.com/r/Philippines/#res:ner-page=2',
      },
      {
        dateAdded: 1522298550525,
        id: 5,
        index: 0,
        parentId: 1,
        title: 'Piracy Megathread v2.0 : Piracy',
        url: 'https://www.reddit.com/r/Piracy/comments/6583hl/piracy_megathread_v20/',
      },
      {
        dateAdded: 1533002645254,
        id: '156',
        index: 4,
        parentId: '144',
        title: 'Overview — Bitbucket',
        url: 'https://bitbucket.org/dashboard/overview',
      },
      {
        dateAdded: 1530972675818,
        id: '19',
        index: 5,
        parentId: '1',
        title: 'Postman - Chrome Web Store',
        url: 'https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop/related?hl=en',
      },
    ],
    dateAdded: 1532501359870,
    dateGroupModified: 1533004793110,
    id: '144',
    index: 0,
    parentId: '1',
    title: 'Pins',
  },
];

export { folderDummyData, recentsDummyData };
